version: '3.8'

services:
  backend:
    image: mcp-tga-server-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tga_store
      - API_BASE_URL=${API_BASE_URL}
      - API_KEY=${API_KEY}
      - SERVER_API_KEY=${SERVER_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tga_store
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tga_store"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: