# render.yaml
# Documentação: https://render.com/docs/blueprint-spec

services:
  # 1. Banco de Dados PostgreSQL
  - type: db
    name: tga-db
    databaseEngine: postgresql
    databaseName: tga_store
    user: user

  # 2. Serviço Web (API Backend)
  - type: web
    name: tga-api-server
    env: docker
    plan: free # ou 'starter' para mais recursos
    healthCheckPath: /health
    envVars:
      # URL do banco de dados provisionado pelo Render (automático)
      - key: DATABASE_URL
        fromService:
          type: db
          name: tga-db
          property: connectionString

      # Variáveis de ambiente que você precisa configurar no Render
      - key: API_BASE_URL
        value: "https://api.tgasistemas.com.br"
      - key: API_KEY
        sync: false
      - key: SERVER_API_KEY
        sync: false