# render.yaml
# Documentação oficial: https://render.com/docs/blueprint-spec

databases:
  - name: tga-db
    databaseName: tga_store
    user: user

services:
  # Serviço Web (API Backend)
  - type: web
    name: tga-api-server
    env: docker
    plan: free # ou 'starter' para mais recursos
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tga-db
          property: connectionString

      # Variáveis de ambiente que você precisa configurar no Render
      - key: API_BASE_URL
        value: "https://api.tgasistemas.com.br"
      - key: API_KEY
        sync: false
      - key: SERVER_API_KEY
        sync: false